#!/bin/bash
set -a
source misc/polybench/.env

./utils/replace_restore.sh replace $COUNTERS ../polybench-c-4.2.1-beta/utilities/papi_counters.list

make clean > /dev/null
python lib/compile.py --import-json config/compile/$ID.json
./lib/run.sh --out-vars $DEP_VARS --runs $RUNS --csv $ID.csv --env-range OMP_NUM_THREADS 1 8 1 --env-file $OMP_ENV
python lib/combine.py --run-info data/csv/run/$ID.csv --compile-info data/csv/compile/compile_$ID.csv  --csv $ID.final.csv
./utils/replace_restore.sh restore ../polybench-c-4.2.1-beta/utilities/papi_counters.list
python3 utils/csv_formatting/format_table.py data/csv/$ID.final.csv
